/* tslint:disable */
/* eslint-disable */
/**
 * Training Plans Api - All Versions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BodyElements = {
    Brzuch: 'Brzuch',
    Biceps: 'Biceps',
    KlatkaPiersiowa: 'KlatkaPiersiowa',
    Plecy: 'Plecy',
    Nogi: 'Nogi',
    Triceps: 'Triceps',
    Poladki: 'Pośladki'
} as const;
export type BodyElements = typeof BodyElements[keyof typeof BodyElements];


export function BodyElementsFromJSON(json: any): BodyElements {
    return BodyElementsFromJSONTyped(json, false);
}

export function BodyElementsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyElements {
    return json as BodyElements;
}

export function BodyElementsToJSON(value?: BodyElements | null): any {
    return value as any;
}

