/* tslint:disable */
/* eslint-disable */
/**
 * Training Plans Api - All Versions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OneCreatedDoneExerciseCommand } from './OneCreatedDoneExerciseCommand';
import {
    OneCreatedDoneExerciseCommandFromJSON,
    OneCreatedDoneExerciseCommandFromJSONTyped,
    OneCreatedDoneExerciseCommandToJSON,
} from './OneCreatedDoneExerciseCommand';

/**
 * 
 * @export
 * @interface CreateDoneExerciseCommand
 */
export interface CreateDoneExerciseCommand {
    /**
     * 
     * @type {number}
     * @memberof CreateDoneExerciseCommand
     */
    userId: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateDoneExerciseCommand
     */
    date: Date;
    /**
     * 
     * @type {Array<OneCreatedDoneExerciseCommand>}
     * @memberof CreateDoneExerciseCommand
     */
    doneExercise: Array<OneCreatedDoneExerciseCommand>;
}

/**
 * Check if a given object implements the CreateDoneExerciseCommand interface.
 */
export function instanceOfCreateDoneExerciseCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "doneExercise" in value;

    return isInstance;
}

export function CreateDoneExerciseCommandFromJSON(json: any): CreateDoneExerciseCommand {
    return CreateDoneExerciseCommandFromJSONTyped(json, false);
}

export function CreateDoneExerciseCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDoneExerciseCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'date': (new Date(json['date'])),
        'doneExercise': ((json['doneExercise'] as Array<any>).map(OneCreatedDoneExerciseCommandFromJSON)),
    };
}

export function CreateDoneExerciseCommandToJSON(value?: CreateDoneExerciseCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'date': (value.date.toISOString().substr(0,10)),
        'doneExercise': ((value.doneExercise as Array<any>).map(OneCreatedDoneExerciseCommandToJSON)),
    };
}

