/* tslint:disable */
/* eslint-disable */
/**
 * Training Plans Api - All Versions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PlansType } from './PlansType';
import {
    PlansTypeFromJSON,
    PlansTypeFromJSONTyped,
    PlansTypeToJSON,
} from './PlansType';

/**
 * 
 * @export
 * @interface CreatePlannedTrainingCommand
 */
export interface CreatePlannedTrainingCommand {
    /**
     * 
     * @type {number}
     * @memberof CreatePlannedTrainingCommand
     */
    plansId: number;
    /**
     * 
     * @type {PlansType}
     * @memberof CreatePlannedTrainingCommand
     */
    plansType: PlansType;
    /**
     * 
     * @type {string}
     * @memberof CreatePlannedTrainingCommand
     */
    dateStart: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePlannedTrainingCommand
     */
    dateEnd: string;
    /**
     * 
     * @type {number}
     * @memberof CreatePlannedTrainingCommand
     */
    userId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreatePlannedTrainingCommand
     */
    trainerId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CreatePlannedTrainingCommand
     */
    groupId?: number | null;
}

/**
 * Check if a given object implements the CreatePlannedTrainingCommand interface.
 */
export function instanceOfCreatePlannedTrainingCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "plansId" in value;
    isInstance = isInstance && "plansType" in value;
    isInstance = isInstance && "dateStart" in value;
    isInstance = isInstance && "dateEnd" in value;

    return isInstance;
}

export function CreatePlannedTrainingCommandFromJSON(json: any): CreatePlannedTrainingCommand {
    return CreatePlannedTrainingCommandFromJSONTyped(json, false);
}

export function CreatePlannedTrainingCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePlannedTrainingCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'plansId': json['plansId'],
        'plansType': PlansTypeFromJSON(json['plansType']),
        'dateStart': json['dateStart'],
        'dateEnd': json['dateEnd'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'trainerId': !exists(json, 'trainerId') ? undefined : json['trainerId'],
        'groupId': !exists(json, 'groupId') ? undefined : json['groupId'],
    };
}

export function CreatePlannedTrainingCommandToJSON(value?: CreatePlannedTrainingCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'plansId': value.plansId,
        'plansType': PlansTypeToJSON(value.plansType),
        'dateStart': value.dateStart,
        'dateEnd': value.dateEnd,
        'userId': value.userId,
        'trainerId': value.trainerId,
        'groupId': value.groupId,
    };
}

