/* tslint:disable */
/* eslint-disable */
/**
 * Training Plans Api - All Versions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateExercisesRecordsCommand
 */
export interface CreateExercisesRecordsCommand {
    /**
     * 
     * @type {number}
     * @memberof CreateExercisesRecordsCommand
     */
    exerciseId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateExercisesRecordsCommand
     */
    userId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateExercisesRecordsCommand
     */
    reps: number;
    /**
     * 
     * @type {number}
     * @memberof CreateExercisesRecordsCommand
     */
    weight: number;
}

/**
 * Check if a given object implements the CreateExercisesRecordsCommand interface.
 */
export function instanceOfCreateExercisesRecordsCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "exerciseId" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "reps" in value;
    isInstance = isInstance && "weight" in value;

    return isInstance;
}

export function CreateExercisesRecordsCommandFromJSON(json: any): CreateExercisesRecordsCommand {
    return CreateExercisesRecordsCommandFromJSONTyped(json, false);
}

export function CreateExercisesRecordsCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExercisesRecordsCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'exerciseId': json['exerciseId'],
        'userId': json['userId'],
        'reps': json['reps'],
        'weight': json['weight'],
    };
}

export function CreateExercisesRecordsCommandToJSON(value?: CreateExercisesRecordsCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exerciseId': value.exerciseId,
        'userId': value.userId,
        'reps': value.reps,
        'weight': value.weight,
    };
}

