/* tslint:disable */
/* eslint-disable */
/**
 * Training Plans Api - All Versions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OneCreatedPlannedExerciseCommand } from './OneCreatedPlannedExerciseCommand';
import {
    OneCreatedPlannedExerciseCommandFromJSON,
    OneCreatedPlannedExerciseCommandFromJSONTyped,
    OneCreatedPlannedExerciseCommandToJSON,
} from './OneCreatedPlannedExerciseCommand';
import type { PlansImage } from './PlansImage';
import {
    PlansImageFromJSON,
    PlansImageFromJSONTyped,
    PlansImageToJSON,
} from './PlansImage';

/**
 * 
 * @export
 * @interface CreatePlansCommand
 */
export interface CreatePlansCommand {
    /**
     * 
     * @type {string}
     * @memberof CreatePlansCommand
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePlansCommand
     */
    description: string;
    /**
     * 
     * @type {PlansImage}
     * @memberof CreatePlansCommand
     */
    image: PlansImage;
    /**
     * 
     * @type {number}
     * @memberof CreatePlansCommand
     */
    authorId: number;
    /**
     * 
     * @type {Array<OneCreatedPlannedExerciseCommand>}
     * @memberof CreatePlansCommand
     */
    plannedExercise: Array<OneCreatedPlannedExerciseCommand>;
}

/**
 * Check if a given object implements the CreatePlansCommand interface.
 */
export function instanceOfCreatePlansCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "image" in value;
    isInstance = isInstance && "authorId" in value;
    isInstance = isInstance && "plannedExercise" in value;

    return isInstance;
}

export function CreatePlansCommandFromJSON(json: any): CreatePlansCommand {
    return CreatePlansCommandFromJSONTyped(json, false);
}

export function CreatePlansCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePlansCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'image': PlansImageFromJSON(json['image']),
        'authorId': json['authorId'],
        'plannedExercise': ((json['plannedExercise'] as Array<any>).map(OneCreatedPlannedExerciseCommandFromJSON)),
    };
}

export function CreatePlansCommandToJSON(value?: CreatePlansCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'image': PlansImageToJSON(value.image),
        'authorId': value.authorId,
        'plannedExercise': ((value.plannedExercise as Array<any>).map(OneCreatedPlannedExerciseCommandToJSON)),
    };
}

