/* tslint:disable */
/* eslint-disable */
/**
 * Training Plans Api - All Versions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OneCreatedDoneExerciseCommand
 */
export interface OneCreatedDoneExerciseCommand {
    /**
     * 
     * @type {number}
     * @memberof OneCreatedDoneExerciseCommand
     */
    exerciseInfoId: number;
    /**
     * 
     * @type {number}
     * @memberof OneCreatedDoneExerciseCommand
     */
    series: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof OneCreatedDoneExerciseCommand
     */
    reps: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof OneCreatedDoneExerciseCommand
     */
    weight: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof OneCreatedDoneExerciseCommand
     */
    rate: number;
    /**
     * 
     * @type {number}
     * @memberof OneCreatedDoneExerciseCommand
     */
    rpe: number;
    /**
     * 
     * @type {number}
     * @memberof OneCreatedDoneExerciseCommand
     */
    brakeSeconds: number;
}

/**
 * Check if a given object implements the OneCreatedDoneExerciseCommand interface.
 */
export function instanceOfOneCreatedDoneExerciseCommand(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "exerciseInfoId" in value;
    isInstance = isInstance && "series" in value;
    isInstance = isInstance && "reps" in value;
    isInstance = isInstance && "weight" in value;
    isInstance = isInstance && "rate" in value;
    isInstance = isInstance && "rpe" in value;
    isInstance = isInstance && "brakeSeconds" in value;

    return isInstance;
}

export function OneCreatedDoneExerciseCommandFromJSON(json: any): OneCreatedDoneExerciseCommand {
    return OneCreatedDoneExerciseCommandFromJSONTyped(json, false);
}

export function OneCreatedDoneExerciseCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneCreatedDoneExerciseCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'exerciseInfoId': json['exerciseInfoId'],
        'series': json['series'],
        'reps': json['reps'],
        'weight': json['weight'],
        'rate': json['rate'],
        'rpe': json['rpe'],
        'brakeSeconds': json['brakeSeconds'],
    };
}

export function OneCreatedDoneExerciseCommandToJSON(value?: OneCreatedDoneExerciseCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exerciseInfoId': value.exerciseInfoId,
        'series': value.series,
        'reps': value.reps,
        'weight': value.weight,
        'rate': value.rate,
        'rpe': value.rpe,
        'brakeSeconds': value.brakeSeconds,
    };
}

