/* tslint:disable */
/* eslint-disable */
/**
 * Training Plans Api - All Versions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PlansDto } from './PlansDto';
import {
    PlansDtoFromJSON,
    PlansDtoFromJSONTyped,
    PlansDtoToJSON,
} from './PlansDto';
import type { PlansType } from './PlansType';
import {
    PlansTypeFromJSON,
    PlansTypeFromJSONTyped,
    PlansTypeToJSON,
} from './PlansType';
import type { UserDetailsDto } from './UserDetailsDto';
import {
    UserDetailsDtoFromJSON,
    UserDetailsDtoFromJSONTyped,
    UserDetailsDtoToJSON,
} from './UserDetailsDto';

/**
 * 
 * @export
 * @interface PlannedTrainingsDto
 */
export interface PlannedTrainingsDto {
    /**
     * 
     * @type {string}
     * @memberof PlannedTrainingsDto
     */
    identifier: string;
    /**
     * 
     * @type {number}
     * @memberof PlannedTrainingsDto
     */
    plansId: number;
    /**
     * 
     * @type {PlansType}
     * @memberof PlannedTrainingsDto
     */
    plansType: PlansType;
    /**
     * 
     * @type {string}
     * @memberof PlannedTrainingsDto
     */
    dateStart: string;
    /**
     * 
     * @type {string}
     * @memberof PlannedTrainingsDto
     */
    dateEnd: string;
    /**
     * 
     * @type {PlansDto}
     * @memberof PlannedTrainingsDto
     */
    plans: PlansDto;
    /**
     * 
     * @type {string}
     * @memberof PlannedTrainingsDto
     */
    createdAt: string;
    /**
     * 
     * @type {UserDetailsDto}
     * @memberof PlannedTrainingsDto
     */
    createdBy: UserDetailsDto;
    /**
     * 
     * @type {number}
     * @memberof PlannedTrainingsDto
     */
    userId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PlannedTrainingsDto
     */
    trainerId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PlannedTrainingsDto
     */
    groupId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PlannedTrainingsDto
     */
    modifiedAt?: string | null;
    /**
     * 
     * @type {UserDetailsDto}
     * @memberof PlannedTrainingsDto
     */
    modifiedBy?: UserDetailsDto;
}

/**
 * Check if a given object implements the PlannedTrainingsDto interface.
 */
export function instanceOfPlannedTrainingsDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "identifier" in value;
    isInstance = isInstance && "plansId" in value;
    isInstance = isInstance && "plansType" in value;
    isInstance = isInstance && "dateStart" in value;
    isInstance = isInstance && "dateEnd" in value;
    isInstance = isInstance && "plans" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "createdBy" in value;

    return isInstance;
}

export function PlannedTrainingsDtoFromJSON(json: any): PlannedTrainingsDto {
    return PlannedTrainingsDtoFromJSONTyped(json, false);
}

export function PlannedTrainingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlannedTrainingsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'plansId': json['plansId'],
        'plansType': PlansTypeFromJSON(json['plansType']),
        'dateStart': json['dateStart'],
        'dateEnd': json['dateEnd'],
        'plans': PlansDtoFromJSON(json['plans']),
        'createdAt': json['createdAt'],
        'createdBy': UserDetailsDtoFromJSON(json['createdBy']),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'trainerId': !exists(json, 'trainerId') ? undefined : json['trainerId'],
        'groupId': !exists(json, 'groupId') ? undefined : json['groupId'],
        'modifiedAt': !exists(json, 'modifiedAt') ? undefined : json['modifiedAt'],
        'modifiedBy': !exists(json, 'modifiedBy') ? undefined : UserDetailsDtoFromJSON(json['modifiedBy']),
    };
}

export function PlannedTrainingsDtoToJSON(value?: PlannedTrainingsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
        'plansId': value.plansId,
        'plansType': PlansTypeToJSON(value.plansType),
        'dateStart': value.dateStart,
        'dateEnd': value.dateEnd,
        'plans': PlansDtoToJSON(value.plans),
        'createdAt': value.createdAt,
        'createdBy': UserDetailsDtoToJSON(value.createdBy),
        'userId': value.userId,
        'trainerId': value.trainerId,
        'groupId': value.groupId,
        'modifiedAt': value.modifiedAt,
        'modifiedBy': UserDetailsDtoToJSON(value.modifiedBy),
    };
}

