/* tslint:disable */
/* eslint-disable */
/**
 * Training Plans Api - All Versions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PlansImage = {
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday',
    Sunday: 'Sunday',
    Push: 'Push',
    Pull: 'Pull',
    Legs: 'Legs',
    Upper: 'Upper',
    Lower: 'Lower'
} as const;
export type PlansImage = typeof PlansImage[keyof typeof PlansImage];


export function PlansImageFromJSON(json: any): PlansImage {
    return PlansImageFromJSONTyped(json, false);
}

export function PlansImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlansImage {
    return json as PlansImage;
}

export function PlansImageToJSON(value?: PlansImage | null): any {
    return value as any;
}

