/* tslint:disable */
/* eslint-disable */
/**
 * Training Plans Api - All Versions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PlannedExercisesDto } from './PlannedExercisesDto';
import {
    PlannedExercisesDtoFromJSON,
    PlannedExercisesDtoFromJSONTyped,
    PlannedExercisesDtoToJSON,
} from './PlannedExercisesDto';
import type { PlansImage } from './PlansImage';
import {
    PlansImageFromJSON,
    PlansImageFromJSONTyped,
    PlansImageToJSON,
} from './PlansImage';
import type { UserDetailsDto } from './UserDetailsDto';
import {
    UserDetailsDtoFromJSON,
    UserDetailsDtoFromJSONTyped,
    UserDetailsDtoToJSON,
} from './UserDetailsDto';

/**
 * 
 * @export
 * @interface PlansDto
 */
export interface PlansDto {
    /**
     * 
     * @type {number}
     * @memberof PlansDto
     */
    identifier: number;
    /**
     * 
     * @type {string}
     * @memberof PlansDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PlansDto
     */
    description: string;
    /**
     * 
     * @type {PlansImage}
     * @memberof PlansDto
     */
    image: PlansImage;
    /**
     * 
     * @type {number}
     * @memberof PlansDto
     */
    authorId: number;
    /**
     * 
     * @type {Array<PlannedExercisesDto>}
     * @memberof PlansDto
     */
    plannedExercise: Array<PlannedExercisesDto>;
    /**
     * 
     * @type {string}
     * @memberof PlansDto
     */
    createdAt: string;
    /**
     * 
     * @type {UserDetailsDto}
     * @memberof PlansDto
     */
    createdBy: UserDetailsDto;
    /**
     * 
     * @type {string}
     * @memberof PlansDto
     */
    modifiedAt?: string | null;
    /**
     * 
     * @type {UserDetailsDto}
     * @memberof PlansDto
     */
    modifiedBy?: UserDetailsDto;
}

/**
 * Check if a given object implements the PlansDto interface.
 */
export function instanceOfPlansDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "identifier" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "image" in value;
    isInstance = isInstance && "authorId" in value;
    isInstance = isInstance && "plannedExercise" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "createdBy" in value;

    return isInstance;
}

export function PlansDtoFromJSON(json: any): PlansDto {
    return PlansDtoFromJSONTyped(json, false);
}

export function PlansDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlansDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'identifier': json['identifier'],
        'name': json['name'],
        'description': json['description'],
        'image': PlansImageFromJSON(json['image']),
        'authorId': json['authorId'],
        'plannedExercise': ((json['plannedExercise'] as Array<any>).map(PlannedExercisesDtoFromJSON)),
        'createdAt': json['createdAt'],
        'createdBy': UserDetailsDtoFromJSON(json['createdBy']),
        'modifiedAt': !exists(json, 'modifiedAt') ? undefined : json['modifiedAt'],
        'modifiedBy': !exists(json, 'modifiedBy') ? undefined : UserDetailsDtoFromJSON(json['modifiedBy']),
    };
}

export function PlansDtoToJSON(value?: PlansDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'identifier': value.identifier,
        'name': value.name,
        'description': value.description,
        'image': PlansImageToJSON(value.image),
        'authorId': value.authorId,
        'plannedExercise': ((value.plannedExercise as Array<any>).map(PlannedExercisesDtoToJSON)),
        'createdAt': value.createdAt,
        'createdBy': UserDetailsDtoToJSON(value.createdBy),
        'modifiedAt': value.modifiedAt,
        'modifiedBy': UserDetailsDtoToJSON(value.modifiedBy),
    };
}

