/* tslint:disable */
/* eslint-disable */
/**
 * Training Plans Api - All Versions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PlansType = {
    Individual: 'Individual',
    Personal: 'Personal',
    Group: 'Group'
} as const;
export type PlansType = typeof PlansType[keyof typeof PlansType];


export function PlansTypeFromJSON(json: any): PlansType {
    return PlansTypeFromJSONTyped(json, false);
}

export function PlansTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlansType {
    return json as PlansType;
}

export function PlansTypeToJSON(value?: PlansType | null): any {
    return value as any;
}

