/* tslint:disable */
/* eslint-disable */
/**
 * Training Plans Api - All Versions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDetailsDto
 */
export interface UserDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof UserDetailsDto
     */
    fullName: string;
}

/**
 * Check if a given object implements the UserDetailsDto interface.
 */
export function instanceOfUserDetailsDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fullName" in value;

    return isInstance;
}

export function UserDetailsDtoFromJSON(json: any): UserDetailsDto {
    return UserDetailsDtoFromJSONTyped(json, false);
}

export function UserDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetailsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fullName': json['fullName'],
    };
}

export function UserDetailsDtoToJSON(value?: UserDetailsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fullName': value.fullName,
    };
}

